[build]
  command = "bundle exec jekyll build"
  publish = "_site"
  ignore = "bash ./build-ignore"

[build.environment]
  RUBY_VERSION = "3.1.4"

[[redirects]]
  from = "/src/*"
  to = "/static/src/:splat"
  status = 200

[[redirects]]
  from = "/tax"
  to = "/static/tax/index.html"
  status = 200

[[redirects]]
  from = "/tax/*"
  to = "/static/tax/:splat"
  status = 200

[[redirects]]
  from = "/btc"
  to = "/static/btc/index.html"
  status = 200

[[redirects]]
  from = "/btc/*"
  to = "/static/btc/:splat"
  status = 200

[[redirects]]
  from = "/ppt"
  to = "/static/ppt/index.html"
  status = 200

[[redirects]]
  from = "/ppt/*"
  to = "/static/ppt/:splat"
  status = 200
